### ISSUE TITLE
Ibuffer Groups (Simple): wrong type of argument listp "none"

### ISSUE THREAD

**Issue by The-BigDaddy** [Bad-ptr/persp-mode.el#106]
#### The problem

Using the [gist for ibuffer groups](https://gist.github.com/Bad-ptr/1aca1ec54c3bdb2ee80996eb2b68ad2d#file-persp-mode-ibuffer-groups-el) and with one perspective open or more I get a backtrace of

```
Debugger entered--Lisp error: (wrong-type-argument listp "none")
  ibuffer-generate-filter-groups(((#<buffer comptia-a.org> . 32) (#<buffer *dashboard*> . 32) (#<buffer bigdaddy> . 32) (#<buffer *scratch*> . 32) (#<buffer *Messages*> . 32)))
  ibuffer-redisplay-engine(((#<buffer comptia-a.org> . 32) (#<buffer *dashboard*> . 32) (#<buffer bigdaddy> . 32) (#<buffer *scratch*> . 32) (#<buffer *Messages*> . 32)) nil)
  ibuffer-update(nil t)
  ibuffer-switch-to-saved-filter-groups("persp-mode")
  (closure (t) nil (persp-add-ibuffer-group) (ibuffer-switch-to-saved-filter-groups "persp-mode"))()
  run-hooks(change-major-mode-after-body-hook special-mode-hook ibuffer-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook special-mode-hook ibuffer-mode-hook))
  run-mode-hooks(ibuffer-mode-hook)
  ibuffer-mode()
  ibuffer(nil)
  funcall-interactively(ibuffer nil)
  #<subr call-interactively>(ibuffer nil nil)
  apply(#<subr call-interactively> ibuffer (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> ibuffer nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (ibuffer nil nil))
  call-interactively(ibuffer nil nil)
  command-execute(ibuffer)

```

#### Steps to reproduce

Make use of the code found in the gist for getting Ibuffer to list only buffers in the current perspective.

`M-x toggle-debug-on-error`

`C-x C-b` or `M-x ibuffer`

Backtrace is given.

#### Expected result

Ibuffer would list buffers in the given perspective.

#### Observed result

Errr well that above backtrace.

#### Information

*Emacs version*: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-11-01

*OS*: Void Linux

*Configuration*: [Here's my configuration for persp](https://pastebin.com/2jgBqvyU). It's without the Ibuffer groups stuff as to get Ibuffer working properly at the moment.

**Comment by Bad-ptr** [comment]
I think this is fixed now. Also see #109
