### ISSUE TITLE
package cl  is deprecated  on emasc 27

### ISSUE THREAD

**Issue by jadestrong** [Bad-ptr/persp-mode.el#107]
I use persp-mode on emacs27 and it will throw a warning `package cl is deprecated`, can `cl-lib` replace it?
`The 'cl' package is now officially deprecated in favor of 'cl-lib'.`
https://github.com/emacs-mirror/emacs/blob/8758c96dc7f252944eb97b95c92081b157084477/etc/NEWS#L601

**Comment by hlissner** [comment]
Made a PR for this: #115
