### ISSUE TITLE
spacemacs daemon cannot shutdown

### ISSUE THREAD

**Issue by mphojele** [Bad-ptr/persp-mode.el#111]
https://github.com/syl20bnr/spacemacs/issues/12873

Hi @Bad-ptr, I use spacemacs, and the spacemacs issue link above is about how the emacs daemon fails to shutdown probably on spacemacs, that is, via systemd or a simple `emacsclient -e "(kill-emacs)"`. I also tried `save-buffers-kill-emacs` and `save-buffers-kill-terminal`, they all yield the same results, emacs just gives a unusual prompt on `recentf buffer modified. Kill anyway?`. So this is a prompt you can't interact unless you launch a new emacsclient to get to it. Gets awkward when you shutting down, cause systemd is finding it hard to kill the emacs daemon.

**Comment by mphojele** [comment]
Oh! Yes, why am I telling you this?
Since I use Spacemacs, I tried debugging this issue by setting up spacemacs with a minimal config call spacemacs-base and then testing each layer in turn to see in which does the issue persist. And it turned out to be the spacemacs-layouts layer. So I looked at the packages in there, I added them in turn to dotspacemacs-excluded-packages, then my founds yielded a high chance of persp-mode causing the issue. Basically i dont know the why and how but I it would be great if you also found it interesting and gave it a quick look

**Comment by mphojele** [comment]
The reproduction guide is in the issue mentioned above. Hope to hear from this project soon :)

**Comment by Bad-ptr** [comment]
Well I tried a lot of different things and I have no idea what is wrong.

// Looks like without spacemacs it works. So I assume it's somehow related to spacemacs layouts code, but I don't familiar with spacemacs codebase.)

**Comment by mphojele** [comment]
Thank you for the reply. I forgot to test it without spacemacs. And yes, I think you are correct in that it might be how persp-mode is configured in spacemacs since I found no similar reported issue in doom-emacs.

**Comment by Bad-ptr** [comment]
This may be fixed
