### ISSUE TITLE
conflict with ivy-posframe

### ISSUE THREAD

**Issue by tshu-w** [Bad-ptr/persp-mode.el#113]
#### Reproduction guide 
actiavate `persp-mode` and use `persp-load-state-for-file` to load last state, run `M-x` and ivy-posframe is broken.

if I run `(posframe-delete-all)`, everything works fine, It seems there perp-mode `persp-load-state-for-file` broke posframe.

<img width="1380" alt="Screen Shot 2020-03-04 at 8 48 18 AM" src="https://user-images.githubusercontent.com/13161779/75836798-f6fb6100-5dfd-11ea-84f6-eb85feb878f9.png">

#### `ivy-posframe` config
```emacs-lisp
(use-package ivy-posframe
  :hook (ivy-mode . ivy-posframe-mode)
  :init
  (setq ivy-posframe-parameters '((left-fringe . 8) (right-fringe . 8))
        ivy-posframe-width 120
        ivy-posframe-display-functions-alist '((swiper . nil)
                                               (complete-symbol . ivy-posframe-display-at-point)
                                               (t . ivy-posframe-display-at-frame-center))))
```
#### System Info :computer:
- OS: darwin
- Emacs: 26.3

**Comment by tshu-w** [comment]
and also company-box.

**Comment by tshu-w** [comment]
and also `company-box` which uses frames to show candidates.

**Comment by Bad-ptr** [comment]
May be this will help:
```elisp
(with-eval-after-load "persp-mode"
  (add-hook
   'after-make-frame-functions
   #'(lambda (f)
       (when (and (boundp 'posframe--frame)
                  (eq f posframe--frame))
         (set-frame-parameter f 'persp-ignore-wconf t)))))
```

**Comment by Bad-ptr** [comment]
Or with latest persp-mode:
```elisp
(add-hook
 'persp-restore-window-conf-filter-functions
   #'(lambda (f p new-f-p)
        (with-selected-frame f
          (or (eq f posframe--frame) (window-dedicated-p)))))
```

**Comment by tshu-w** [comment]
I'm sorry, I will try in my free time, perhaps next February 😹️

**Comment by linbinchen** [comment]
> Or with latest persp-mode:
> 
> ```emacs-lisp
> (add-hook
>  'persp-restore-window-conf-filter-functions
>    #'(lambda (f p new-f-p)
>         (with-selected-frame f
>           (or (eq f posframe--frame) (window-dedicated-p)))))
> ```

Had the same issue here, solved by using the second snippet suggested. Thanks!

**Comment by tshu-w** [comment]
Since @linbinchen has tried it for me, I will close this issue.
