### ISSUE TITLE
Problems with windows with no-delete-other-windows param

### ISSUE THREAD

**Issue by czikus** [Bad-ptr/persp-mode.el#120]
My perspectives include windows with `no-delete-other-windows` set to t. When switching perspectives, these windows are not properly removed by `persp-delete-other-windows`, leading to inconsistencies in window configuration. Advising `persp-delete-other-windows` to set `ignore-window-parameters` solves the issue:

```
(defadvice! pronobis/persp-delete-other-windows-advice (orig-fun)
    :around #'persp-delete-other-windows
    (let ((ignore-window-parameters t))
      (funcall orig-fun)))
```

**Comment by Bad-ptr** [comment]
Thanks. Must be fixed 298df111f081b5925f0aa0126a1b8d334117e0a2
