### ISSUE TITLE
Provide old name as initial input to interactive rename of perspective

### ISSUE THREAD

**Issue by joelnoomi** [Bad-ptr/persp-mode.el#127]
When renaming a perspective, I often find the new name to be just a slightly modified version of the old name. Currently, I have to type out the whole new name whereas it would have been more convenient to simply edit the old name.

I suggest the old name be provided as initial input in the `(read-string)` call at:
https://github.com/Bad-ptr/persp-mode.el/blob/298df111f081b5925f0aa0126a1b8d334117e0a2/persp-mode.el#L2870

That is:

```elisp
        (unless new-name
          (setq new-name
                (read-string
                 (concat "New name for the " old-name " perspective: ") old-name)))
```

In case I want to start over and type the new name all the way from scratch, it is easy enough to kill the initial input with something like <kbd>C-a k</kbd> or <kbd>M-backspace</kbd>.

What do you think? Is there perhaps a (reasonable) way of achieving this behavior without modifying persp-mode.el that I have overlooked?

**Comment by Bad-ptr** [comment]
> What do you think? 

I agree with you. It will be a good addition.
