### ISSUE TITLE
Error running timer: (void-function make-persp-internal)

### ISSUE THREAD

**Issue by CestDiego** [Bad-ptr/persp-mode.el#18]
I get this when enable persp-mode in the *Messages* buffer

**Comment by Bad-ptr** [comment]
This is strange. Probably you have installed both [persp-mode.el](https://github.com/Bad-ptr/persp-mode.el) and [perspective-el](https://github.com/nex3/perspective-el). If that the case -- you must choose one of these and uninstall another.

Anyway you could launch emacs with -Q and --debug-init, then manually load persp-mode.el (`M-x load-file RET /path/to/persp-mode.el RET`) and find a way to reproduce that bug.
Also it will be interesting to know what version of emacs you are using(`M-: (message "%s" emacs-version) RET`) and which packages you have installed (`M-: (message "%s" package-activated-list) RET`)

**Comment by CestDiego** [comment]
The problem is that I was using use-package. Using the :no-require flag makes it work better. 
```
  (use-package persp-mode
    :no-require t
    :init
    :config
    ;; switch off the animation of restoring window configuration
    (persp-mode 1))
```

**Comment by CestDiego** [comment]
I'll close the issue because I got this working with the above code ^
