### ISSUE TITLE
Skipping should be first in persp-save-buffer-functions

### ISSUE THREAD

**Issue by mz-pdm** [Bad-ptr/persp-mode.el#20]
The default value of persp-save-buffer-functions contains Tramp file handling before running persp-filter-save-buffers-functions. That means checks in persp-filter-save-buffers-functions have no effect on Tramp files by default. This is both confusing and inconvenient. I suggest moving the buffer skip checking code to the first position in persp-save-buffer-functions.

**Comment by Bad-ptr** [comment]
You are right.

**Comment by Bad-ptr** [comment]
Fixed in 228ad6b5d63baff4f53079f8c75f809d3758ed77.
