### ISSUE TITLE
Type error in persp-common-buffer-filter-functions

### ISSUE THREAD

**Issue by mz-pdm** [Bad-ptr/persp-mode.el#28]
The recent commit "Fix filtering out helm buffers." introduces the call

(string-prefix-p "Helm" (buffer-local-value 'mode-name b))

However mode-name is not always string, e.g. it's a list in Org Agenda. In such a case this call signals an error. This may make under some circumstances Emacs unusable, so please fix that with high priority.

**Comment by Bad-ptr** [comment]
Hope this dae604c1116663bd462184868397a420676a77d9 will help.

**Comment by mz-pdm** [comment]
Thanks. Looks fine to me although I haven't chance to test it yet (current persp-mode still not completely working for me).
