### ISSUE TITLE
No replacement for switch-to-buffer and display-buffer advices

### ISSUE THREAD

**Issue by mz-pdm** [Bad-ptr/persp-mode.el#30]
I don't know what's the motivation for removal of those advices. Maybe there is some good reason behind it but I miss them a lot! A typical example is using Gnus perspective where all the created summaries, articles, etc. are marked as being outside my perspective. There are other usage scenarios like that.
Sure, I can define my own advices but that should be documented as having this functionality may be very important to some users and the otherwise excellent persp-mode is much less useful without it. And please, please, be more conservative with changes like that next time -- the change broke my workflow and I had to spend significant time investigating what happened.

**Comment by Bad-ptr** [comment]
Motivation is that the advices is not a good way to do things(however sometimes it's the only way).
I don't know how many people have used this feature(I have not used it). The warning about possibility of removing advices was in the docstring of the `persp-add-on-switch-or-display` variable.
Well, I think I'l revert that change.

**Comment by mz-pdm** [comment]
I can understand some reluctance to use advices and you're right about the warning in the docstring -- I probably had decided to try the feature anyway and then forgot about the warning, my fault. I still consider it being a useful feature but maybe I use persp-mode in a wrong way, I'll think about it.

**Comment by mz-pdm** [comment]
I'm experimenting with not using those advices and using major mode hooks instead. I'm not sure about that approach yet, but so far it seems to provide better buffer placement to perspectives for the price of more configuration.

**Comment by Bad-ptr** [comment]
I decided to put instructions to the README.md and let the users to deal with it. :)
