### ISSUE TITLE
persp-mode prevents magit commit buffer from opening in current non-primary frame

### ISSUE THREAD

**Issue by aaronjensen** [Bad-ptr/persp-mode.el#39]
## Repro

1. From magit's source, `make emacs-Q`
2. Execute:

    ```elisp
    (add-to-list 'load-path "path-to-persp-mdoe")
    (require 'persp-mode)
    (persp-mode)
    (require 'server)
    (setq server-name "foo")
    (server-start)
    ```
3. Then, in a terminal:

    ```bash
    emacsclient --tty -s $TMPDIR/emacsXXX/foo some_file_in_git_control
    ```
4. Make a change to the file.
5. `M-x magit-status`
6. Stage the file with `s`
7. `c c`

## Expected

You should see the commit buffer and the diff buffer in the tty frame.

## Actual

You only see diff buffer. If you `C-x C-#` the frame closes and takes you to the gui emacs and the commit buffer appears.

**Comment by Bad-ptr** [comment]
Please test the https://github.com/Bad-ptr/persp-mode.el/tree/ignore-magit-server-switch branch.

**Comment by aaronjensen** [comment]
This seems to work, thank you!

**Comment by Bad-ptr** [comment]
> This seems to work

nice to hear

> thank you!

thanks for testing
