### ISSUE TITLE
persp-mode ignores old buffer-predicate in new frame?

### ISSUE THREAD

**Issue by bmag** [Bad-ptr/persp-mode.el#41]
I'm trying to use a custom non-persp-mode-related `buffer-predicate` frame parameter together with persp-mode. From what I understand, this should be enough:
```elisp
(push '(buffer-predicate . my-predicate) default-frame-alist)
(set-frame-parameter nil 'buffer-predicate 'my-predicate) ; I'm not sure if this is needed
(persp-mode)
```
And now `C-x <right>` (`next-buffer`) and friends should consider both persp-mode's predicate and my custom predicate. However, if I create a new frame, the command `next-buffer` ignores my custom predicate in the new frame.

*Reproduction recipe*:
- Create a file `temp.el` with this content:
```elisp
(setq persp-auto-resume-time -1)

(defun my-test-func (buffer)
  (message "Test: %s" buffer)
  t)

(push '(buffer-predicate . my-test-func) default-frame-alist)
(set-frame-parameter nil 'buffer-predicate 'my-test-func)
(require 'persp-mode)
(persp-mode)
```
- run emacs: `emacs -Q -L ~/.emacs.d/elpa/persp-mode-20160609.1316/ -l temp.el &`
- create new frame: `C-x 5 2` (`make-frame-command`)
- check values of frame parameters `buffer-predicate` and `buffer-predicate-old`

*Observed values*:
In first frame:
- buffer-predicate: `my-test-func`
- buffer-predicate-old: `my-test-func`

In second frame:
- buffer-predicate: `#[(b)
  "\303\304\305p!\"\203^K^@\306\207\307\310 	\n\306$>\207"
  [b *persp-restrict-buffers-to* persp-restrict-buffers-to-if-foreign-buffer string-prefix-p " " buffer-name t persp-buffer-list-restricted selected-frame]
  6]`
- buffer-predicate-old: `my-test-func`

*Expected values*:
In first frame: I don't know what to expect
In second frame: `buffer-predicate` should contain a call to `my-test-func`, according to the code in `persp-set-frame-buffer-predicate`:
```elisp
(case old-pred
  ;; --- snipped ---
  (t
   (if persp-frame-buffer-predicate
       #'(lambda (b)
           (and
            (funcall persp-frame-buffer-predicate b)
            (funcall old-pred b)))
     old-pred)))
```

**Comment by Bad-ptr** [comment]
Yes, you are right. This needs to be fixed.

**Comment by Bad-ptr** [comment]
Hope this will work for most cases 255273b33f2246aaa82ea95900e71b3647b0664b .

**Comment by bmag** [comment]
It seems to work, thank you :smiley:
