### ISSUE TITLE
Unrelated buffers killed on find-alternate-file

### ISSUE THREAD

**Issue by mz-pdm** [Bad-ptr/persp-mode.el#42]
When I run C-x C-v (find-alternate-file), unrelated buffers may be killed by side effect. When inspecting it I've found out that the problem disappears when I remove persp-kill-buffer-h from kill-buffer-hook. It seems that persp-kill-buffer-h switches buffers in the middle of find-alternate-file and then another buffer, in addition to the current one, gets killed during the operation.
It's possible to watch the bug in action by switching to some perspective, instrumenting find-alternate-file for debugging and running C-x C-v. In the debugger, step until you reach (run-hooks 'kill-buffer-hook) line in find-alternate-file and observe that the current buffer gets switched after evaluating the line.

**Comment by Bad-ptr** [comment]
Confirmed.

**Comment by Bad-ptr** [comment]
Seems like fixed 05b53251fefad5a0ab1deda4d9613b656a9e583b.

**Comment by mz-pdm** [comment]
At the first glance, it seems to fix the bug. Thanks!
