### ISSUE TITLE
How to save some buffers starting with '*'

### ISSUE THREAD

**Issue by jwintz** [Bad-ptr/persp-mode.el#43]
As I understand the documentation, 

> You must prepend that function to the persp-save-buffer-functions list (before the standard filtering functions cause it filters buffers starting with the '*').

However, to me, the whole point to using perspectives is to get back my `*eshell*`, `*magit*` and `*compilation*` buffers together with my files, whenever I load a previously saved perspective, cause it saves a lot of time.

How can I add functions to save and restore them anyway ?

**Comment by jwintz** [comment]
I have tried to set `persp-filter-save-buffers-functions` to `nil`, and if my windows are correctly loaded, their minor mode is not. I have the following snippet in my saved perspective:

```
(def-buffer "*magit: .prolusion.d" nil magit-status-mode)
```

And in the window configuration:

```
(buffer "*magit: .prolusion.d" (selected) (hscroll . 0) (fringes 8 0 nil) (margins nil) (scroll-bars nil 0 t nil 0 nil) (vscroll . 0) (dedicated) (point . 301) (start . 1))
```

But the magit buffer is not set up correctly.

**Comment by Bad-ptr** [comment]
> I have tried to set persp-filter-save-buffers-functions to nil

This is not so easy. You must define custom save/load functions as shown here:
https://github.com/Bad-ptr/persp-mode.el#custom-saveload-buffer-function-example

I can take a look at your wishes, but not on this or next week.)

Meantime you can describe in more detail what do you want.  For example if you want to save an `*eshell*` buffer you probably want to save a current directory with it, etc.
And what do you expect from saving `*compilation*` buffer? Do you want a content(compiler messages) of this buffer to be saved?

**Comment by jwintz** [comment]
Thanks Constantin ! I'm not yet very proficient in emacs lisp but I'll give it a shot.

In the meantime here is what I would like to tweak:

- saving the `*eshell*` buffers together with their respective mode, names (using `multi-eshell`, I have a lot of them) and current directories (I think the history will come for free as it is built-in eshell-mode)

- saving the `*compilation*` buffers together with their respective mode, names, current directories and the build commands, same here, I have a lot of them, distinguished by `M-x rename-buffer`

- saving the `*magit*` buffers together with their respective mode (status, log, etc..), names, and current directories. Of course, I nearly have to or three of them per perspective.

**Comment by Bad-ptr** [comment]
I added the `def-persp-buffer-save/load` function 2346982e2d181977a9cf189a7f446eddf07a6397.
I think this will work for you:
```elisp
  (def-persp-buffer-save/load :mode 'eshell-mode :tag-symbol 'def-eshell-buffer
    :save-vars '(major-mode default-directory))
  (def-persp-buffer-save/load :mode 'compilation-mode :tag-symbol 'def-compilation-buffer
    :save-vars '(major-mode default-directory compilation-directory compilation-environment))
  (with-eval-after-load "magit-autoloads"
    (require 'magit)
    (def-persp-buffer-save/load :mode 'magit-status-mode :tag-symbol 'def-magit-status-buffer
      :save-vars '(major-mode default-directory)
      :after-load-function #'(lambda (b) (with-current-buffer b (magit-refresh)))))
```

**Comment by Bad-ptr** [comment]
ok, I consider You are satisfied with it)
