### ISSUE TITLE
read-multiple-choice is not bound on Emacs 25.1 RC2

### ISSUE THREAD

**Issue by zilongshanren** [Bad-ptr/persp-mode.el#44]

**Comment by Bad-ptr** [comment]
Hmm you are right.
As a quick fix you can copy it to your counfig
https://github.com/emacs-mirror/emacs/blob/ad90397c599034a5f2a977baf9d04802f986eee2/lisp/emacs-lisp/subr-x.el#L201

**Comment by zilongshanren** [comment]
@Bad-ptr  thanks, I will give it a try.

**Comment by zilongshanren** [comment]
@Bad-ptr  it works, thanks.
