### ISSUE TITLE
Perspectives no longer automatically save on exit (in Spacemacs)

### ISSUE THREAD

**Issue by gilbertw1** [Bad-ptr/persp-mode.el#45]
I recently noticed that perspectives have stopped auto saving altogether in Spacemacs. After some digging I've tracked down [this commit](
https://github.com/Bad-ptr/persp-mode.el/commit/f6f24750132883b3fac377c93edbec4c437be872) as the source of the problem.

After reverting this commit perspectives have again begun to save again properly in Spacemacs. I'm not yet sure if this is a bug that needs to be fixed in this project or spacemacs, I've created [bug there as well](https://github.com/syl20bnr/spacemacs/issues/7105).

Thanks!

**Comment by TheBB** [comment]
It's probably our (Spacemacs') problem since we don't run that hook when exiting.

**Comment by Bad-ptr** [comment]
Ok, actually I think now that the right way will be to save perspectives in both kill-emacs-query-functions(try to save and query user on failure, remove emacs-kill-hook on success) and emacs-kill-hook(try to save and exit ignoring errors).

**Comment by Bad-ptr** [comment]
Must be fixed in https://github.com/Bad-ptr/persp-mode.el/commit/633bb2d266d5fcc4d69258e34a7d57ad5fa49f26.

**Comment by gilbertw1** [comment]
Awesome, thank you! Just tested it locally and it works perfectly.
