### ISSUE TITLE
Warning: (lambda (b) ...) quoted with ' rather than with #'

### ISSUE THREAD

**Issue by GreyGhostIX** [Bad-ptr/persp-mode.el#46]
When loading the package I am getting this warning.
`Warning: (lambda (b) ...) quoted with ' rather than with #'`.

Interestingly it didn't seem to break my perspective functionality, but it did seem to be responsible for some other seemingly unrelated problems I was having.

It is possible it is  related to [this issue](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=11357). [This reddit thread](https://www.reddit.com/r/emacs/comments/54jpl9/warning_lambda_b_quoted_with_rather_than_wits/) also discusses this issue.

**Comment by Bad-ptr** [comment]
probably fixed(not really, but maybe *Compile-Log* will not pop up into view) in d79b9785e288fb313e51c0ebbd1eb8c18675a51b

**Comment by Bad-ptr** [comment]
More proper fix a89e1f6b18a1ab56915b5b1943d09a016b36bacc

**Comment by GreyGhostIX** [comment]
Awesome, thanks so much!
