### ISSUE TITLE
Saving layouts by name broken

### ISSUE THREAD

**Issue by jluttine** [Bad-ptr/persp-mode.el#47]
I get the following error when trying to choose layouts in "save layouts by name": `Wrong type argument: keymapp, nil`

I experienced the issue in Spacemacs and was asked to report it upstream. Please see the following issue for details: https://github.com/syl20bnr/spacemacs/issues/7207

**Comment by Bad-ptr** [comment]
Hope this will help 3d3b1f7e5ac20a870f1d9c6992f5a4b0e3f80ad6

**Comment by jluttine** [comment]
Yes, now it seems to work. Thanks a lot!
