### ISSUE TITLE
Emacs doesn't exit when persp-auto-save-opt is non-zero

### ISSUE THREAD

**Issue by nandryshak** [Bad-ptr/persp-mode.el#49]
When `persp-auto-save-opt` is 0, `persp-asave-on-exit` will return `nil`, which makes `persp-kill-emacs-query-function` return `nil`, which prevents `save-buffers-kill-emacs` from finishing, which means Emacs never exits, because `save-buffers-kill-emacs` runs `persp-kill-emacs-query-function` using `run-hook-with-args-until-failure`, and `nil` indicates a failure.

Phew, that was a mouthful. I submitted a pull request that fixes this by returning `t` when auto-save is off, indicating a successful completion of the function.

**Comment by Bad-ptr** [comment]
Thanks.
However I did additional changes 93202a6d9b823eb21361bf911c01bbf91898a6e2. Hope this will not break your fix.)

**Comment by nandryshak** [comment]
Hmm, I think it might break again. Changing the `when` to an `if` should fix it.

**Comment by Bad-ptr** [comment]
@nandryshak can I close this? Or do you think that it is still not fixed?

**Comment by nandryshak** [comment]
I believe it should be fixed now, thanks!
