### ISSUE TITLE
Order of loaded perspectives is inconsistent

### ISSUE THREAD

**Issue by bmag** [Bad-ptr/persp-mode.el#53]
It seems that if I save some perspectives to file with `persp-save-to-file-by-names`, and in later Emacs sessions I load that file with `persp-load-state-from-file`, then the order of perspectives (as returned  by `persp-names-current-frame-fast-ordered`) is inconsistent . For some reason, if I save with `persp-save-state-to-file` instead of  `persp-save-to-file-by-names`, then the order is consistent (at least in the scenario I tried).

Original report: https://github.com/syl20bnr/spacemacs/issues/7396

**Reproduction guide :beetle:**

- save this file as `test-init.el`:
```elisp
(require 'package)
(package-initialize)
(setq persp-auto-resume-time -1)
(require 'persp-mode)
(persp-mode)
```
- start emacs: <kbd>emacs -Q -l test-init.el</kbd>
- create persp foo: <kbd>M-x persp-switch foo</kbd>
- create persp bar: <kbd>M-x persp-switch bar</kbd>
- get persps: <kbd>M-: (persp-names-current-frame-fast-ordered)</kbd>. Output: `("none" "foo" "bar")`
- save persps `foo` and `bar` to file `foobar`: <kbd>M-x persp-save-to-file-by-names foo bar [\<done\>] foobar</kbd>
- exit emacs: <kbd>C-x C-c</kbd>
- start emacs: <kbd>emacs -Q -l test-init.el</kbd>
- load persps: <kbd>M-x persp-load-state-from-file foobar</kbd>
- get persps: <kbd>M-: (persp-names-current-frame-fast-ordered)</kbd>. Output: `("none" "bar" "foo")`
- exit emacs: <kbd>C-x C-c</kbd>
- start emacs: <kbd>emacs -Q -l test-init.el</kbd>
- load persps: <kbd>M-x persp-load-state-from-file foobar</kbd>
- get persps: <kbd>M-: (persp-names-current-frame-fast-ordered)</kbd>. Output: `("none" "foo" "bar")`

**Observed behaviour: :eyes: :broken_heart:**

Output of `(persp-names-current-frame-fast-ordered)` is inconsistent. It alternates between `("none" "foo" "bar")` and `("none" "bar" "foo")`.

**Expected behaviour: :heart: :smile:**

Output of `(persp-names-current-frame-fast-ordered)` should be consistent - `("none" "foo" "bar")` everytime.

**Comment by Bad-ptr** [comment]
possibly fixed 4aac831b911a475ff68fe27642213b7a4c6ac34d

**Comment by bmag** [comment]
I can confirm that it is fixed, at least for this set of names. We did get a report on spacemacs (https://github.com/syl20bnr/spacemacs/issues/7459) that the order is consistent, but it doesn't reflect the order in which the perspectives were created. I'm not sure if that is supposed to be a supported feature, though, because I didn't see persp-mode's documentation talking about the order of perspectives.

In the linked report, `SPC l <number>` calls `persp-switch`, `SPC l S` calls `persp-save-to-file-by-names`, `SPC l L` calls `persp-load-state-from-file`, and the order is the same as returned by `persp-names-current-frame-fast-ordered` (and "layout" means "perspective", as you probably know already).

**Comment by jluttine** [comment]
Yep, I can confirm that the alternating order issue has been fixed. However, previously my layout order was preserved when saving, not anymore. So I'm guessing that some recent changes have broken that (if that is even something that was supposed to be supported). Or is there some other way how to set the order of layouts (perspectives?)?

**Comment by Bad-ptr** [comment]
@jluttine your issue must be fixed now

**Comment by bmag** [comment]
@jluttine after you install the updated `persp-mode`, can you report if the issue is fixed, and then I'll close both issues (this one and the one in spacemacs)?

**Comment by jluttine** [comment]
I tested now and it seems to work. Thanks!
