### ISSUE TITLE
README : Spacemacs link broken

### ISSUE THREAD

**Issue by mandarvaze** [Bad-ptr/persp-mode.el#54]
README refers to ``funcs.el`` in spacemacs project, but looks like the link it broken due to refactoring of the spacemacs code.

Since I can't see current link, I do not know whether or not you mean to point to https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-layouts/funcs.el 
(If this is correct, I can send a PR)

**Comment by Bad-ptr** [comment]
> Since I can't see current link, I do not know whether or not you mean to point to https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-layouts/funcs.el (If this is correct, I can send a PR)

Yes, I think it is correct.

**Comment by Bad-ptr** [comment]
must be fixed.
