### ISSUE TITLE
Automatic Tests

### ISSUE THREAD

**Issue by bmag** [Bad-ptr/persp-mode.el#55]
Follow up to https://github.com/syl20bnr/spacemacs/issues/7409#issuecomment-254163195, where you wrote:

> I have no automatic tests

Do you want help with setting up automatic tests? I had good experience using Travis CI with a stack of [cask](https://github.com/cask/cask), [buttercup](https://github.com/jorgenschaefer/emacs-buttercup) (test writer and runner), [evm](https://github.com/rejeep/evm)(emacs installer for CI) and [undercover](https://github.com/sviridov/undercover.el) (elisp coverage tool). I can set it up for you, if you want.

For an example, you can look at [window-purpose develop branch](https://github.com/bmag/emacs-purpose/tree/develop), and specifically these files: `.travis.yml`, `Makefile`, `Cask` and the `tests` directory. (`.ert-runner` and `test` directory are remnants of the previous stack I used, that I haven't removed yet)

**Comment by Bad-ptr** [comment]
> I had good experience using Travis CI with a stack of cask, buttercup (test writer and runner), evm(emacs installer for CI) and undercover (elisp coverage tool).
> For an example, you can look at window-purpose develop branch, and specifically these files: .travis.yml, Makefile, Cask and the tests directory. (.ert-runner and test directory are remnants of the previous stack I used, that I haven't removed yet)

Thanks for the info.
However when I start to think about writing tests my thoughts jump to an idea of a complete rewrite of the persp-mode. I'm not sure that I want to invest much time on writing tests for the persp-mode(and persp-mode itself) for now. But maybe some basic tests, just to be sure that user can start and quit emacs without a problem, will worth it.

> I can set it up for you, if you want.

It will be great.)

**Comment by bmag** [comment]
PR opened at #56
