### ISSUE TITLE
alist-get isn't defined in Emacs 24.5 and older

### ISSUE THREAD

**Issue by bmag** [Bad-ptr/persp-mode.el#62]
Recent commit https://github.com/Bad-ptr/persp-mode.el/commit/b764ecaa5efef784aea23cf552a38e8417189ef1 uses `alist-get`, but `alist-get` was only introduced in Emacs 25.1, so now `persp-mode` breaks on older emacsen.

Related issue report: https://github.com/syl20bnr/spacemacs/issues/7782

**Comment by Bad-ptr** [comment]
Must be fixed in 2ab3c6b86527811794235309df6055b4a302aa76

**Comment by bmag** [comment]
Thank you very much :smile:
