### ISSUE TITLE
Keep persp-mode from interfering with kill-buffer

### ISSUE THREAD

**Issue by Stebalien** [Bad-ptr/persp-mode.el#70]
How do I get persp-mode to stop interfering with kill-buffer. I've set `persp-kill-foreign-buffer-behavior` to `'kill` but it's still asking: "Remove the ... buffer from all perspectives?". I'm guessing the problem is that the buffer isn't foreign.

FYI, I'm using spacemacs if it makes a difference.

To reproduce, make two auto-persps, enter the first, open a buffer that automatically belongs to the second, and then kill it (never leaving the first perspective).

**Comment by Bad-ptr** [comment]
OK, you can try the [develop branch](https://github.com/Bad-ptr/persp-mode.el/tree/develop) for now.
(see the [`persp-remove-buffers-from-nil-persp-behaviour`](https://github.com/Bad-ptr/persp-mode.el/commit/a271cf6812ce5893dae876f2851c1849f798898c#diff-ad587a8d68b99fcd1d26681ee77cccffR511) variable)
I will merge this to master in the end of the week(if I don't find any bugs).

**Comment by Stebalien** [comment]
Well, now it doesn't ask but... I can't kill the buffer at all!

**Comment by Bad-ptr** [comment]
Indeed, you can not kill a buffer that belongs to a perspective from another perspective.
It needs to be fixed.)

**Comment by Bad-ptr** [comment]
I think I have fixed this 52b813a8a31c12fe0e5a5e5e2fd3e408b495887b

**Comment by Stebalien** [comment]
It never actually gets to `persp--kill-buffer-query-function-foreign-check` as `(persp-contain-buffer-p buffer persp)` returns `t` (everything belongs to the `nil` buffer). Unfortunately, this means `foreign-check-passed gets set to `t` and, further down, `(eq 'kill foreign-check-passed)` is `nil`.

**Comment by Bad-ptr** [comment]
Yes, you are right. Thanks. I just committed a (possible:)) fix.

**Comment by Stebalien** [comment]
Thanks! It appears to work now.

(I'm leaving this open in case you prefer to keep issues open until
fixed in master.)

**Comment by Bad-ptr** [comment]
I have changed the code a bit https://github.com/Bad-ptr/persp-mode.el/commit/c0249bd2201e361c55bbbab978a28dab288f6bd6
Hope this will not break it for you).

**Comment by Stebalien** [comment]
I haven't noticed any regressions.

**Comment by Bad-ptr** [comment]
Fixed in master, closing this.
