### ISSUE TITLE
Switching buffers in kill-buffer-hook

### ISSUE THREAD

**Issue by mz-pdm** [Bad-ptr/persp-mode.el#71]
persp-mode adds persp-kill-buffer-h to kill-buffer-hook. It invokes persp--remove-buffer-1, which may switch buffers. In the result other kill-buffer-hook functions may be called on a different buffer than the killed one, which may cause undesirable effects.

Setting persp-when-remove-buffer-switch-to-other-buffer to nil in persp-kill-buffer-h seems to fix the problem.

**Comment by Bad-ptr** [comment]
Can you try this a81eee3accf8c624a0956356364fd7a2566a91f3 ?

**Comment by mz-pdm** [comment]
I tried it and it seems to work fine. Thank you for the fix!

**Comment by Bad-ptr** [comment]
must be fixed
