### ISSUE TITLE
Restoring shell

### ISSUE THREAD

**Issue by LucaMarconato** [Bad-ptr/persp-mode.el#76]
Is there any way yo make perspective restore also shell sessions?

However, congratulation for this beautiful package!

**Comment by LucaMarconato** [comment]
It would be cool if also the buffer *compilation* and all the similar buffer were restored!

**Comment by Bad-ptr** [comment]
Did you read(and tried) this https://github.com/Bad-ptr/persp-mode.el#custom-saveload-buffer-function-example ?
If you have any questions feel free to ask.

**Comment by simonmichael** [comment]
Thanks for persp-mode!

Out of the box persp-mode saves an entry like this in persp-confs/persp-auto-save for a shell-mode buffer named "1":
```
(def-buffer "1" nil shell-mode)
```
I tried to understand the custom save examples and the undocumented but useful-looking persp-def-buffer-save/load function. After doing:
```
(persp-def-buffer-save/load
 :mode 'shell-mode
 :tag-symbol 'def-shell
 :save-vars '(major-mode default-directory)
)
```
it saves an entry like:
```
    (def-shell "1"
      ((major-mode . shell-mode)
       (default-directory . "~/")))
```
Either of these causes it to complain at startup:
```
[persp-mode] Error: Can not autoresume perspectives -- (wrong-type-argument processp nil)
```

It's very common to have shells and many other weird kinds of buffer - it would be great to handle more of them out of the box, and to do something more helpful with unsupported buffers, eg emit a less scary warning on load, or better, skip them when saving.

**Comment by Bad-ptr** [comment]
More examples :-)
https://gist.github.com/Bad-ptr/1aca1ec54c3bdb2ee80996eb2b68ad2d#file-persp-erc-el-L4
https://gist.github.com/Bad-ptr/1aca1ec54c3bdb2ee80996eb2b68ad2d#file-persp-multi-term-el-L5

You need to write a custom load function, to run `shell`(not `shell-mode`) function for the buffer.

**Comment by simonmichael** [comment]
I saw those. Actually I'm not even trying to start a shell at this point. I'd be happy if it simply created the empty buffer without complaining. Clearly I don't understand your API.

**Comment by Bad-ptr** [comment]
Ok, then you can test the [develop](https://github.com/Bad-ptr/persp-mode.el/tree/develop) branch.
With this setup:

```elisp
(persp-def-buffer-save/load
 :mode 'shell-mode
 :mode-restore-function #'(lambda (_mode) (shell)) ; or #'identity if you do not want to start shell process
 :tag-symbol 'def-shell
 :save-vars '(major-mode default-directory))
```

**Comment by Bad-ptr** [comment]
> test the develop branch.

Now it's merged into master. And it seem to work for me.)
