### ISSUE TITLE
default previous buffer suggestion for `persp-switch-to-buffer`

### ISSUE THREAD

**Issue by LucaMarconato** [Bad-ptr/persp-mode.el#77]
I have remapped C-x b to `persp-switch-to-buffer` but I find really annoying that when I press return without typing anything I do not go to the previously opened buffer in the current perspective.
It would be very useful to add that possibility. Is there any simple way to do that?
The same behaviour would be also appreciated when I want to switch perspective, so I can get to the perspective in which I was working prior to change perspective.

Thanks

**Comment by Bad-ptr** [comment]
Must be fixed 15355c1fee8a569401193d2ef412b7fa42a2885c

**Comment by LucaMarconato** [comment]
Working perfectly, thank you, your package is impressive!
