### ISSUE TITLE
Feature request: re-arranging perspectives

### ISSUE THREAD

**Issue by agzam** [Bad-ptr/persp-mode.el#78]
How difficult would it be to implement this? It would be awesome to have it. Thanks!

**Comment by Bad-ptr** [comment]
https://github.com/Bad-ptr/persp-mode.el#changing-the-order-of-the-perspectiveshow-it-looks-when-you-are-prompted-for-a-perspective-names

**Comment by agzam** [comment]
It seems that introduced a bug, check this out, please: https://github.com/syl20bnr/spacemacs/issues/9544

**Comment by agzam** [comment]
@Bad-ptr Thanks for fixing it. It appears to be working fine in Spacemacs/develops. Let's wait for a couple of days for any feedback, If everything's fine this ticket may be closed.
