### ISSUE TITLE
`C-x k' kills buffer still present in other perspectives

### ISSUE THREAD

**Issue by mz-pdm** [Bad-ptr/persp-mode.el#79]
When a buffer is present in more than one perspective and I kill it with `C-x k', it's really killed rather than just removed from the current perspective.

How to reproduce:

- Switch to some buffer in some perspective.
- Switch to another perspective.
- Add the buffer to the current perspective.
- Kill the buffer with `C-x k'.
- Switch back to the original perspective.
- The buffer is not there.

I think the problem is in persp-kill-buffer-query-function, `not-foreign' branch:

    (if (persp-buffer-in-other-p* buffer persp)
        (persp--remove-buffer-2 persp buffer)

persp--remove-buffer-2, and thus persp-kill-buffer-query-function, returns the buffer rather than nil so the buffer gets actually killed. If I change the code above to

    (if (persp-buffer-in-other-p* buffer persp)
        (progn
          (persp--remove-buffer-2 persp buffer)
          nil)

then killing buffers works as expected.

**Comment by Bad-ptr** [comment]
You are correct. Thanks!

**Comment by Bad-ptr** [comment]
Must be fixed 8d397d2c8d09db6b8a000c1d76df81ce5ea9963a

**Comment by mz-pdm** [comment]
Thanks for quick fix!
