### ISSUE TITLE
[feature-request] `list-buffers` for current perspective

### ISSUE THREAD

**Issue by LucaMarconato** [Bad-ptr/persp-mode.el#80]
When I didn't know persp-mode I used to call `list-buffers` for killing all the buffers which I didn't need anymore, in a fast way.
With persp-mode calling `list-buffers` shows all the opened buffers, so when I am using a lot of perspectives it is difficult to handle buffers.
It would be useful to have the function `persp-list-buffers`. I think the implementation would be very fast.

**Comment by Bad-ptr** [comment]
See the https://github.com/Bad-ptr/persp-mode.el#universal

```elisp
(defun persp-list-buffers (&optional arg)
  (interactive "P")
  (with-persp-buffer-list () (list-buffers arg)))
```

**Comment by LucaMarconato** [comment]
Oh it is very simple, thank you!
