### ISSUE TITLE
bug: current file overwritten if using `persp-save-to-file` without specifying the filename

### ISSUE THREAD

**Issue by LucaMarconato** [Bad-ptr/persp-mode.el#83]
If you try to save the perspectives state using `persp-save-to-file` without specifying the file name (let's say using `C-c p w RET`, the current state will be written in the file of the currently open buffer.
By luck you will no lose data you save the buffer (since it is still open) or if you look at the auto recovery file.

**Comment by Bad-ptr** [comment]
must be fixed ccf87da2c230c3a91e627105b0f034a954e6842a

**Comment by LucaMarconato** [comment]
great!
