### ISSUE TITLE
Can a buffer be prevented from appearing on created frames?

### ISSUE THREAD

**Issue by Alexander-Miller** [Bad-ptr/persp-mode.el#84]
I am currently in the process of changing my [treemacs](https://github.com/Alexander-Miller/treemacs) package such that every treemacs buffer is bound to and only shown in a single frame. I've now run into the issue with persp-mode where creating a frame when a treemacs window is visible leads to the same window and buffer showing in the created frame. Is there a way to prevent this from happening? 

Just not showing specific buffers in new frames would be enough for my purposes, but I'm also interested whether it's possible to just fully exclude treemacs buffers from persp's layout management, since the way treemacs is set up - either one global buffer now, or frame-local buffers later - does not really fit in with the persp's layout concept.

**Comment by Bad-ptr** [comment]
> I am currently in the process of changing my treemacs package such that every treemacs buffer is bound to and only shown in a single frame.

How are you going to achieve this?

> I've now run into the issue with persp-mode where creating a frame when a treemacs window is visible leads to the same window and buffer showing in the created frame. Is there a way to prevent this from happening?

I think you can add a function to the `persp-activated-functions` or `after-make-frame-functions`(append in that case) in which you can check for visibility of the buffers and switch/hide(delete window) them.

> whether it's possible to just fully exclude treemacs buffers from persp's layout management, since the way treemacs is set up - either one global buffer now, or frame-local buffers later - does not really fit in with the persp's layout concept.

"persp's layout concept" is based on emacs' "window-state" (`window-state-get`/`-set` functions).
The most you can do now is to add a filter function to the `persp-common-buffer-filter-functions`(however it will not help much).

**Comment by Bad-ptr** [comment]
You can also around advice `window-state-get` function.
Hiding your buffer before `window-state-get` and restoring after.

**Comment by Alexander-Miller** [comment]
> How are you going to achieve this?

It's a simple setup: whenever I need to show or grab a treemacs buffer I go through an alist mapping frames to buffers (removing those entries and killing frames' buffers when frames are deleted). Technically all those frame-local buffers are still in your buffer-list, but they're kept buried, and when was the last time you manually switched to something like neotree instead of calling neotree-show?

> I think you can add a function to the persp-activated-functions or after-make-frame-functions(append in that case) in which you can check for visibility of buffers and switch/hide(delete window) them.

Going for after-make-frame-functions was my first idea, but it didn't work since the persp code ran after the treemacs code. persp-activated-functions is just what I needed. There's still interference from persp/eyebrwose glue code in spacemacs, but  treemacs is removed correctly otherwise.

For now I have all the tools I need. Thanks for the help.
