### ISSUE TITLE
Kill buffer without persp-mode prompt

### ISSUE THREAD

**Issue by LucaMarconato** [Bad-ptr/persp-mode.el#89]
When I press `C-x k` to kill a buffer which is not in the current perspective, persp-mode will ask me if I am sure, which a message like:
`You are going to kill a buffer(<buffername>) which is not in the current(<current perspective name>) perspective. It will be removed from (<others perspective name>) perspectives and then killed. What do you really want to do? ([q] - do nothing; [k] - kill; [K] - kill and close window; [s] - switch to another buffer):`

I tried to suppress this prompt and opt for the default kill [k] behaviour inserting this line in my emacs configuration:

`(setq persp-kill-foreign-buffer-behaviour-choices 'kill)`.

It does not work, what am I doing wrong?

**Comment by Bad-ptr** [comment]
use `(setq persp-kill-foreign-buffer-behaviour 'kill)`
