### ISSUE TITLE
persp-add-new: Symbol's function definition is void: make-persp-internal

### ISSUE THREAD

**Issue by delexi** [Bad-ptr/persp-mode.el#9]
Trying to create a new perspective will result in the following error:
`persp-add-new: Symbol's function definition is void: make-persp-internal`

Steps to reproduce:
- `emacs -q`
- Eval the following code:

``` lisp
(add-to-list 'load-path "/home/delexi/.emacs.d/elpa/workgroups-20110726.941")
(add-to-list 'load-path "/home/delexi/.emacs.d/elpa/persp-mode-20140119.1113")
(require 'persp-mode)
(persp-mode 1)
```
- Execute `M-x persp-switch` and type e.g. "test" RET

This is emacs24.3

EDIT: Funny thing: I just "edebuged" persp-add-new and the stepping through somehow did _not_ trigger the error. I was able to create a new perspective "test". After this, creating perspectives is on longer a problem. After restarting emacs this problem resurfaces.

**Comment by vincentjgoh** [comment]
I've just installed 2.9.6 from MELPA stable, and this is happening to me. Exact same error message. workgroups was not installed.

**Comment by Bad-ptr** [comment]
@vincentjgoh 
> workgroups was not installed

Maybe you have perspective-el installed then?
