### ISSUE TITLE
"Cannot make side window the only window" on persp-restore-window-conf

### ISSUE THREAD

**Issue by hlissner** [Bad-ptr/persp-mode.el#90]
If the current window is a side window, and you attempt to switch perspectives (via `persp-switch`), the following error occurs: `Cannot make side window the only window`, leaving persp-mode in a broken state.

+ side windows are a new feature in Emacs 26. They can be detected via the `window-side` window parameter and opened with `display-buffer-in-side-window`.
+ The error is caused by calling `delete-other-windows` from a side window.
+ The error originates from `persp-restore-window-conf`, which calls `delete-other-windows` [on line 3567](https://github.com/Bad-ptr/persp-mode.el/blob/master/persp-mode.el#L3565-L3568).

### Steps to reproduce

1. Opens Emacs 26+
2. Create a new perspective: `(persp-add-new "X")` (don't switch to it)
3. Create and select the side window:
  ```elisp
  (let* ((buffer (get-buffer-create "*temp*"))
         (window (display-buffer-in-side-window buffer '((side . bottom)))))
    (select-window window))
  ```
4. Switch to the "X" workspace via `M-x persp-switch`.

-----

I'm not sure how you want to handle this edge case. The workaround I am currently using is:

```elisp
  (defun select-non-side-window (&rest _)
    "Ensure a side window isn't current when switching workspaces."
    (when (window-parameter nil 'window-side)
      (select-window
       (cl-loop for win in (window-list)
                unless (window-parameter win 'window-side)
                return win))))
  (add-hook 'persp-before-deactivate-functions #'select-non-side-window)
```

**Comment by Bad-ptr** [comment]
Thanks for detailed bug report.
Can you test the [develop](https://github.com/Bad-ptr/persp-mode.el/tree/develop) branch fea610580fc748125dd431d9173cded14394f9b1 ?

**Comment by hlissner** [comment]
Sorry for the late reply. fea6105 has been working without issue!

**Comment by Bad-ptr** [comment]
ok, then it must be fixed
