### ISSUE TITLE
"emacscleint -c" (or call to make-frame) set perspectives of all frame to "#none"

### ISSUE THREAD

**Issue by mgcyung** [Bad-ptr/persp-mode.el#97]
A new frame created by "emacsclient -c" will set perspectives of all
frames include pre-exist frames to "#none".

**Comment by mgcyung** [comment]
It is caused by that "emacsclient -c" will load custom.el and there is
entry in custom-set-variables to load persp-mode. However persp-mode
will reset the current perspectiv list.

**Comment by Bad-ptr** [comment]
interesting

**Comment by Bad-ptr** [comment]
Must be fixed 689f63e7370cd9424d84b9f7b2eb3d1955443313
